using System;
using System.Collections.Generic;

namespace Cs.Problems
{
    /// <title>Pentagonal Numbers</title>
    /// <summary>
    /// Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
    /// 
    /// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
    /// 
    /// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
    /// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and
    /// D = |Pk - Pj| is minimised; what is the value of D?
    /// </summary>
    public class Problem044 : IProblem
    {
        private HashSet<long> Pentagonals = new HashSet<long>();
        private int LastN = 1;
        private long LastPentagonal = 1;

        public bool IsPentagonal(long test)
        {
            var batch = test * 10;
            while (LastPentagonal < batch)
            {
                LastN += 1;
                LastPentagonal = (LastN * (3 * LastN - 1)) >> 1;
                Pentagonals.Add(LastPentagonal);
            }

            return Pentagonals.Contains(test);
        }

        private bool Meets(int a, int b)
        {
            var penta = (3 * a * a - a);
            var pentb = (3 * b * b - b);
            return IsPentagonal((penta - pentb) >> 1) && IsPentagonal((penta + pentb) >> 1);
        }

        private Tuple<int,int> BruteSolve()
        {
            for (var i = 1; ; i += 1)
            for (var j = i - 1; j > 0; j--)
            if (Meets(i, j))
            {
                return Tuple.Create(i, j);
            }
        }

        public string Solve()
        {
            var answer = BruteSolve();
            var a = answer.Item1;
            var b = answer.Item2;
            var d = ((3 * a * a - a) - (3 * b * b - b)) >> 1;
            return d.ToString();
        }
    }
}
