/// Aaron Johnson
/// 2016-11-13

/// Even Fibonacci Numbers
/// Each new term in the Fibonacci sequence is generated by adding
/// the previous two terms. By starting with 1 and 2, the first 10 terms will be:
///
/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
///
/// By considering the terms in the Fibonacci sequence whose values do not exceed
/// four million, find the sum of the even-valued terms.

struct Fib(i32, i32);

impl Iterator for Fib {
    type Item = i32;
    fn next(&mut self) -> Option<Self::Item> {
        *self = Fib(self.1, self.0 + self.1);
        Some(self.0)
    }
}

pub fn solve() -> i32 {
    Fib(0, 1).take_while(|x| *x < 4000000).filter(|x| x % 2 == 0).sum()
}