# Even Fibonacci Numbers
#
# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

problem02 <- function() {
	current <- c(0,1)
	total <- 0
	while (current[1] < 4e+6) {
		if (current[1] %% 2 == 0) {
			total <- total + current[1]
		}
		current <- c(current[2], current[1]+current[2])
	}

	total
}

fib <- function() {
	fib_ <- function(a) {
	    val <- c(a[2], a[1] + a[2])
	    list(getnext=function() fib_(val),
	    	 current=val[1])
	}
	fib_(c(0,1))
}

problem02_alt <- function() {
	fib <- fib()
	total <- 0
	while (fib$current < 4e+06) {
		if (fib$current %% 2 == 0) {
			total <- total + fib$current
		}
		fib <- fib$getnext()
	}

	total
}
