using System.Linq;

namespace euler
{
    /// <title>Even Fibonacci Numbers</title>
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding 
    /// the previous two terms. By starting with 1 and 2, the first 10 terms will be: 
    /// 
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// 
    /// By considering the terms in the Fibonacci sequence whose values do not exceed
    /// four million, find the sum of the even-valued terms.
    /// </summary>
    /// <answer>4613732</answer>
    public class Problem002 : IProblem
    {
        static int Solve(int maxFibValue)
        {
            return Sequences.Fibonacci().Where(x => x % 2 == 0).TakeWhile(x => (x < maxFibValue)).Sum();
        }
        public string Solve()
        {
            return Solve(4000000).ToString();
        }
    }
}
