/**
  * Created by aaron on 8/14/2016.
  */

package Problems

/** Solve Euler Problem 2: Even Fibonacci Numbers
  *
  * Each new term in the Fibonacci sequence is generated by adding
  * the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  *
  * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  *
  * By considering the terms in the Fibonacci sequence whose values do not exceed
  * four million, find the sum of the even-valued terms.
  */
class Problem002 extends Problem {
  def solve: String = Sequences.fibonacci
    .filter(n => n % 2 == 0)
    .takeWhile(n => n < 4000000)
    .sum
    .toString
}
